# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Red teaming configuration

# Docs: https://promptfoo.dev/docs/red-team/configuration
description: "IONET intelligence red team configuration"

targets:
  # Red team targets. To talk directly to your application, use a custom provider.
  # See https://promptfoo.dev/docs/red-team/configuration/#providers
  - id: https
    label: Iointel Meta LLama 3.3
    config:
      url: "https://api.intelligence.io.solutions/api/v1/chat/completions"
      method: "POST"
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer {{api_key}}"
      body:
        model: "meta-llama/Llama-3.3-70B-Instruct"
        messages:
          - role: "system"
            content: "You are a helpful assistant."
          - role: "user"
            content: "{{prompt}}"
  - id: https
    label: Iointel Meta Deepseek R1
    config:
      url: "https://api.intelligence.io.solutions/api/v1/chat/completions"
      method: "POST"
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer {{api_key}}"
      body:
        model: "meta-llama/Llama-3.3-70B-Instruct"
        messages:
          - role: "system"
            content: "You are a helpful assistant."
          - role: "user"
            content: "{{prompt}}"


tests:
  - vars:
      year: 1950
  - vars:
      year: 1984
  - vars:
      year: 2020
  - vars:
      year: 2023

# # Other redteam settings
# redteam:
#   purpose: "Application hosts different foundation models for the customers"
  
#   # Default number of inputs to generate for each plugin.
#   # The total number of tests will be (numTests * plugins.length * (1 + strategies.length) * languages.length)
#   # Languages.length is 1 by default, but is added when the multilingual strategy is used.
#   numTests: 5

#   # Each plugin generates 5 adversarial inputs.
#   # To control the number of tests for each plugin, use:
#   # - id: plugin-name
#   #   numTests: 10
#   plugins:
#     # - contracts  # Tests for unauthorized contractual commitments and legal exposure
#     # - excessive-agency  # Tests for unauthorized actions beyond defined system boundaries
#     - hallucination  # Tests for fabrication of false or misleading information
#     # - harmful:chemical-biological-weapons  # Tests handling of WMD-related content
#     # - harmful:child-exploitation  # Tests handling of child exploitation content
#     # - harmful:copyright-violations  # Tests handling of intellectual property violations
#     # - harmful:cybercrime  # Tests handling of cybercrime-related content
#     # - harmful:cybercrime:malicious-code  # Tests creation of malicious code
#     # - harmful:graphic-content  # Tests handling of graphic or violent content
#     # - harmful:harassment-bullying  # Tests handling of harassment and bullying content
#     # - harmful:hate  # Tests handling of hate speech and discriminatory content
#     # - harmful:illegal-activities  # Tests handling of general illegal activities
#     # - harmful:illegal-drugs  # Tests handling of illegal drug-related content
#     # - harmful:illegal-drugs:meth  # Tests handling of methamphetamine-related content
#     # - harmful:indiscriminate-weapons  # Tests handling of weapons-related content
#     - harmful:insults  # Tests handling of personal attacks and insults
#     # - harmful:intellectual-property  # Tests handling of IP theft and violations
#     # - harmful:misinformation-disinformation  # Tests handling of false information campaigns
#     # - harmful:non-violent-crime  # Tests handling of non-violent criminal content
#     # - harmful:privacy  # Tests handling of privacy violation attempts
#     # - harmful:profanity  # Tests handling of profane or inappropriate language
#     # - harmful:radicalization  # Tests handling of extremist content and recruitment
#     # - harmful:self-harm  # Tests handling of self-harm and suicide content
#     # - harmful:sex-crime  # Tests handling of sexual crime content
#     # - harmful:sexual-content  # Tests handling of explicit sexual content
#     # - harmful:specialized-advice  # Tests handling of unauthorized professional advice
#     # - harmful:unsafe-practices  # Tests handling of dangerous activity instructions
#     # - harmful:violent-crime  # Tests handling of violent crime content
#     # - harmful:weapons:ied  # Tests handling of Improvised Explosive Devices
#     # - hijacking  # Tests for unauthorized resource usage and purpose deviation
#     # - pii:api-db  # Tests for PII exposure via API/database access
#     # - pii:direct  # Tests for direct PII exposure vulnerabilities
#     # - pii:session  # Tests for PII exposure in session data
#     # - pii:social  # Tests for PII exposure via social engineering
#     # - politics  # Tests handling of political content and bias
    
#   # Attack methods for applying adversarial inputs
#   strategies:
#     - basic # Original plugin tests without any additional strategies or optimizations
#     # - jailbreak # Single-shot optimization of safety bypass techniques
#     # - jailbreak:composite # Combines multiple jailbreak techniques for enhanced effectiveness
    
  